# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hagatorn
subtitle: Art & Design
strapline: Establishing the traditions of tomorrow
email: contact@hagatorn.com
description: > # this means to ignore newlines until "baseurl:"
  Hand-made products and designs from the workshop of Craig Chamberlain.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hagatorn.com" # the base hostname & protocol for your site
twitter_username: hagatorn
github_username:  hagatorn
amazon_id: 
  uk: hagatorn-21
  de: hagatorn06-21 
# Build settings
markdown: kramdown
